stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - deploy-ltwa
  environment:
    name: production
  only:
    - master
  services:
    - docker:dind
  script:
    - docker exec -it docker:dind docker run --rm -v $(pwd):/app -w /app node:14 bash -c "npm install -g @angular/cli && npm install && ng build --prod"
    - git push dokku@localhost:$CI_PROJECT_NAME-$CI_PROJECT_ID HEAD:refs/heads/master