stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - deploy-ltwa
  environment:
    name: production
  only:
    - master
  script:
    - docker pull your-angular-image:latest
    - docker run --rm -v $(pwd):/app -w /app your-angular-image:latest npm install
    - docker run --rm -v $(pwd):/app -w /app your-angular-image:latest ng build --prod
    - git push dokku@localhost:$CI_PROJECT_NAME-$CI_PROJECT_ID HEAD:refs/heads/master