stages:
  - setup
  - build
  - deploy

variables:
  DOKKU_HOST: dokku.example.com # Replace with your Dokku server hostname

setup:
  stage: setup
  script:
    - apt-get update -qy
    - apt-get install -y nodejs npm
    - npm install -g @angular/cli

build:
  stage: build
  script:
    - npm install
    - ng build --prod

deploy:
  stage: deploy
  tags:
    - deploy-ltwa
  environment:
    name: production
  only:
    - master
  script:
    - git push dokku@localhost:$CI_PROJECT_NAME-$CI_PROJECT_ID HEAD:refs/heads/master
