image: node:14

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - apt-get update -qy
    - apt-get install -y nodejs npm
    - npm install -g @angular/cli
    - npm install
    - ng build --prod

deploy:
  stage: deploy
  tags:
    - deploy-ltwa
  environment:
    name: production
  only:
    - master
  script:
    - git push dokku@localhost:$CI_PROJECT_NAME-$CI_PROJECT_ID HEAD:refs/heads/master
