image: node:20

stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
  script:
    - apt-get update -qy
    - npm install -g @angular/cli
    - npm install
    - ng build --configuration=production

deploy:
  stage: deploy
  tags:
    - deploy-ltwa
  environment:
    name: production
  only:
    - master
  script:
    - git-push master
